apiVersion: v1
kind: Secret
metadata:
  name: trinetra-config
  namespace: monitoring
type: Opaque
stringData:
  config.yaml: |
    jobs:
      - name: "check-disk-space"
        schedule: "*/5 * * * *"
        script: |
          #!/bin/sh
          df -h | grep '/$' | awk '{print $5}' | sed 's/%//'
        logic:
          and:
            - ">": [{"var": "result"}, 80]
        labels:
          severity: warning
          component: disk
    
      - name: "check-memory-usage"
        schedule: "*/5 * * * *"
        script: |
          #!/bin/sh
          free | grep Mem | awk '{print $3/$2 * 100.0}'
        logic:
          and:
            - ">": [{"var": "result"}, 85]
        labels:
          severity: warning
          component: memory 