apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: trinetra
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: trinetra
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics 